repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        log_file: ".artifacts/flake8.pycodestyle.log"
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        python_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.19
    hooks:
      - id: isort
        python_version: python3.7
        additional_dependencies: [toml]
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
        exclude_types: [svg]
      - id: trailing-whitespace
        exclude_types: [svg]
      - id: debug-statements
      - id: requirements-txt-fixer
