name: GitHub CI
on: [push, pull_request]

jobs:
  test:
    name: test suite python {{ matrix.python }}, node {{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [ '2.7' ]
        node: [ '8.15.1' ]
        os: [ 'ubuntu-16.04' ]
    services:
      postgresql:
        image: postgres:9.6-alpine
        ports:
          - 5432:5432
      redis:
        # idk what redis version we're pinned to
        image: redis:5.0-alpine
        ports:
          - 6379:6379
    steps:
    - name: Install Dependencies (system)
      run: |
        sudo apt-get install -y libxmlsec1-dev libgeoip-dev
        CHROME_MAJOR_VERSION="$(dpkg -s google-chrome-stable | sed -nr 's/Version: ([0-9]+).*/\1/p')"
        wget -N "https://chromedriver.storage.googleapis.com/$(curl https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION})/chromedriver_linux64.zip" -P ~/
        unzip ~/chromedriver_linux64.zip -d ~/
        rm ~/chromedriver_linux64.zip
        sudo install -m755 ~/chromedriver /usr/local/bin/
    # TODO: how to get the sha of the latest pushed commit?
    - uses: actions/checkout@master
    - name: Install Dependencies (node)
      env:
        YARN_VERSION: '1.13.0'
      run: |
        npm install -g "yarn@{YARN_VERSION}"
    - uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python }}
        architecture: x64
    - name: Install Dependencies (python)
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: on
      run: |
        python -m pip install pip==19.1.1
        make install-tests
        python -m pip install codecov
    - name: Test and Build
      run: |
        psql -c 'create database sentry;' -U postgres
        make lint
        py.test --cov . --cov-report="xml:.artifacts/coverage.xml" --junit-xml=".artifacts/junit.xml" --html="artifacts/pytest.html" || exit 1
